MANDT	ZTR2R_AA_MIGRCUS	MANDT		MANDT	CLNT	3	Мандант
AFABE	ZTR2R_AA_MIGRCUS	AFABE		BF_AFABE_D	NUMC	2	Реальная область оценки
STRNAME	ZTR2R_AA_MIGRCUS	STRNAME		STRUKNAME	CHAR	30	Имя структуры
FIELDNAME	ZTR2R_AA_MIGRCUS	FIELDNAME		NAME_KOMP	CHAR	30	Имя компонента
NUMPP	ZTR2R_AA_MIGRCUS	NUMPP		NUMC3	NUMC	3	Numc3, внутр. использование
ROLLNAME	DD03L	ROLLNAME		ROLLNAME	CHAR	30	Элемент данных (семантический домен)
CONVEXIT	DD01L	CONVEXIT		CONVEXIT	CHAR	5	Подпрограмма преобразования
INTTYPE	DD03L	INTTYPE		INTTYPE	CHAR	1	ABAP-тип данных (C,D,N,...)
DATATYPE	DD01L	DATATYPE		DATATYPE_D	CHAR	4	Тип данных в ABAP-словаре
LENG	DD01L	LENG		DDLENG	NUMC	6	Длина (число знаков)
ENTITYTAB	DD01L	ENTITYTAB		ENTITYTAB	CHAR	30	Таблица значений
